version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: kcm-postgres
    environment:
      POSTGRES_DB: kcm_db
      POSTGRES_USER: kcm_user
      POSTGRES_PASSWORD: kcm_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:6.2
    container_name: kcm-redis
    ports:
      - "6379:6379"

  kcm-api:
    image: kafkaetech/kcm-api:latest
    container_name: kcm-api
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
    environment:
      # App identity
      KCM_APP_NAME: "kcm-manager"
      KCM_APP_VERSION: "1.0.0"

      # Security: Default user
      KCM_DEFAULT_USER_ENABLED: "true"
      KCM_DEFAULT_PASSWORD: "admin"

      # License
      KCM_LICENSE_PATH: "/app/license/license.json"
      KCM_LICENSE_KAFKA_TOPIC: "__kcm_license"
      KCM_LICENSE_SIGNATURE_PATH: "/app/license/license.sig"
      KCM_LICENSE_HISTORY_DIR: "/app/license/license-history"

      # Encryption keys
      KCM_ENCRYPT_PRIVATE_KEY: "/app/keys/private.pem"
      KCM_ENCRYPT_PUBLIC_KEY: "/app/keys/public.pem"

      # JWT
      KCM_JWT_PERSISTENCE_MODE: "JDBC"
      KCM_JWT_TOKEN_VALIDITY: "86400"
      KCM_JWT_PRIVATE_KEY: "/app/keys/private.pem"
      KCM_JWT_PUBLIC_KEY: "/app/keys/public.pem"

      # App file storage
      KCM_APP_FILES_PATH: "/app/files"

      # PostgreSQL
      KCM_DB_URL: "jdbc:postgresql://postgres:5432/kcm_db"
      KCM_DB_USER: "kcm_user"
      KCM_DB_PWD: "kcm_password"

      # Kafka
      KCM_ADMIN_CLIENT_ID: "kc-admin-client"

      # Redis
      SPRING_REDIS_HOST: "redis"
      SPRING_REDIS_PORT: "6379"
      SPRING_REDIS_DATABASE: "0"
      SPRING_REDIS_TIMEOUT: "2000"

    volumes:
      - ./data/keys:/app/keys
      - ./data/files:/app/files

  kcm-ui:
    image: kafkaetech/kcm-ui:latest
    container_name: kcm-ui
    depends_on:
      - kcm-api
    ports:
      - "80:80"
    volumes:
      - ./runtime-config.json:/usr/share/nginx/html/runtime-config.json:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  pgdata:
  kcm-license:
  kcm-keys:
  kcm-files: